### ISSUE TITLE
/api/v1/fracdiff tests

### ISSUE THREAD

**Issue by unrealwork** [axibase/jmeter-xml-to-jmx-converter#3]
Related to axibase/tsd#1668

Add a few perf tests for manually defined and auto `d` cases, under volume bars: https://github.com/axibase/jmeter-xml-to-jmx-converter/blob/input/input.xml#L6530

_Originally posted  in https://github.com/axibase/tsd/issues/1668#issuecomment-856969312_

**Comment by rodionos** [comment]
fin-fracdiff-auto-d - replace now with fixed dates. Otherwise, the row count difference may trigger an alert. Also add tests for various periods. Reduce interval for fin-fracdiff-auto-d, so that each query takes less than 5 seconds (now it's 12 seconds).
